# Generating Experimentatl Dataset
The objective of this code is to take the paramaters given by industry knowledge and generate a dataset to be used to guide collection of experimental results to ensure unbiased, all-eoncompassing data

In [30]:
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import pandas as pd
from random import *
import math
from IPython.display import display

#### Reads in data to ensure compatibility of synthetic and real dataset

In [31]:
df = pd.read_csv('../DataSets/deviceSummary.csv')
columns = list(df.columns)
print(columns)

['devices', 'Temperature', 'Speed', 'Distance', 'Pressure', 'Efficiency']

In [32]:
def getRange(regions, tempMin, tempMax):
    tempRange = tempMax - tempMin
    tempIncrements = tempRange / regions
    tempBins = []
    for i in range(4):
        tempBins.append(int(tempMin + tempIncrements*i))
    tempBins.append(tempMax)
    return tempBins

In [33]:
bins = 4
temperatureRange, speedRange, distanceRange, pressureRange = getRange(bins, 50, 80), getRange(bins, 125, 200), getRange(bins, 500, 800), getRange(bins, 0, 100)
print(temperatureRange)
print(speedRange)
print(distanceRange) # Multiplied by 100 to prevent decimals
print(pressureRange) # Multiplied by 10 to prevent decimals

[50, 57, 65, 72, 80]
[125, 143, 162, 181, 200]
[500, 575, 650, 725, 800]
[0, 25, 50, 75, 100]

In [34]:
distance = [5, 6, 7, 8]
speed = [125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200]
temp = [50, 55, 60, 65, 70, 75, 80]
pressure = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

totalCombos = len(distance) * len(speed) * len(temp) * len(pressure)
print(len(speed))
print(len(temp))
print(totalCombos)

16
7
4928

In [35]:
newDF = pd.DataFrame(columns=['Temperature','Speed','Distance','Pressure','Efficiency'])
trialNum = 1
for i in distance:
    for j in speed:
        for k in temp:
            for l in pressure:
                newDF = newDF.append({'Temperature' : k, 'Speed' : j, 'Distance':i, 'Pressure':l, 'Efficiency' : 0.0}, 
                ignore_index = True)
                trialNum += 1
display(newDF)
newDF.to_csv('../DataSets/machineAcceptingOptimizedSynthetic.csv')

      Temperature  Speed  Distance  Pressure  Efficiency
0            50.0  125.0       5.0       0.0         0.0
1            50.0  125.0       5.0       1.0         0.0
2            50.0  125.0       5.0       2.0         0.0
3            50.0  125.0       5.0       3.0         0.0
4            50.0  125.0       5.0       4.0         0.0
...           ...    ...       ...       ...         ...
4923         80.0  200.0       8.0       6.0         0.0
4924         80.0  200.0       8.0       7.0         0.0
4925         80.0  200.0       8.0       8.0         0.0
4926         80.0  200.0       8.0       9.0         0.0
4927         80.0  200.0       8.0      10.0         0.0

[4928 rows x 5 columns]

In [36]:

display(newDF)
newDF.to_csv('newDataCollection6.csv')

      Temperature  Speed  Distance  Pressure  Efficiency
0            50.0  125.0       5.0       0.0         0.0
1            50.0  125.0       5.0       1.0         0.0
2            50.0  125.0       5.0       2.0         0.0
3            50.0  125.0       5.0       3.0         0.0
4            50.0  125.0       5.0       4.0         0.0
...           ...    ...       ...       ...         ...
4923         80.0  200.0       8.0       6.0         0.0
4924         80.0  200.0       8.0       7.0         0.0
4925         80.0  200.0       8.0       8.0         0.0
4926         80.0  200.0       8.0       9.0         0.0
4927         80.0  200.0       8.0      10.0         0.0

[4928 rows x 5 columns]